phases:
  pre_build:
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
      - echo installing dependencies...
  build:
    commands:
      - npm install
      - echo "testing......"
      - ./node_modules/mocha/bin/mocha
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"