version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10

jobs:
  unit_test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/with-cache:
          steps:
            - run: npm install
      - run: 
          name: Running unit tests
          command: npm test -- --grep "UNIT TESTS" --exit
  integration-test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/with-cache:
          steps:
            - run: npm install
      - run:
          name: Running script to prepare integration tests
          command: node ./prepare/prepareIT.js 
      - run: 
          name: Running Integration tests
          command: npm test -- --grep "INTEGRATION TESTS" --exit


workflows:
  test-deploy:
    jobs:
      - unit_test:
          matrix:
            parameters:
              node-version: ["14.4.0"]
      - integration-test:
          matrix:
            parameters:
              node-version: ["14.4.0"]
      - heroku/deploy-via-git:
          requires:
            - integration-test
          filters:
            branches:
              only: master