version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm test -- --grep "unit tests" --exit
  deploy:
    docker:
      - image: 14.4.0-stretch-slim
    environment:
      NODE_ENV: production 
    steps:
      - run: echo Installing heroku cli
      - run: npm install -g heroku
      - run: heroku --version
    
workflows:
  test-deploy:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["14.4.0"]
      - deploy:
          requires:
            - test