version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/with-cache:
          steps:
            - run: npm install
      - run: 
          name: Running unit tests
          command: npm test -- --grep "unit tests" --exit

workflows:
  test-deploy:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["14.4.0"]
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: master