version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm test -- --grep "unit tests" --exit
  deploy:
    docker:
      - image: node:14.4.0-alpine3.12
    steps:
      - run: echo "Installing heroku cli"
      - run: npm install -g heroku
      - run: heroku --version
      - run: echo "installing git"
      - run: apk add --no-cache git
      - checkout
      - run: echo "Deploying project on heroku"
      - run: heroku git:remote -a employee-backend-bogota
      - run: git push heroku $CIRCLE_BRANCH:master 
    
workflows:
  test-deploy:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["14.4.0"]
      - deploy:
          requires:
            - test